// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/whoami.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function db(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var whoami_default = defineTool({
  name: "whoami",
  title: "\u0645\u0646 \u0623\u0646\u0627",
  description: "Return the signed-in user's profile, role, and office assignment.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = db(ctx);
    const userId = ctx.getUserId();
    const [{ data: profile, error: pErr }, { data: roleRow }] = await Promise.all([
      supabase.from("profiles").select("*").eq("id", userId).maybeSingle(),
      supabase.from("user_roles").select("role").eq("user_id", userId).maybeSingle()
    ]);
    if (pErr) return { content: [{ type: "text", text: pErr.message }], isError: true };
    const payload = { userId, email: ctx.getUserEmail(), role: roleRow?.role ?? null, profile };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-offices.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
function db2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_offices_default = defineTool2({
  name: "list_offices",
  title: "\u0642\u0627\u0626\u0645\u0629 \u0627\u0644\u0645\u0643\u0627\u062A\u0628",
  description: "List all operational offices the signed-in user is permitted to see.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await db2(ctx).from("offices").select("*").order("id");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { offices: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-daily-reports.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function db3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_daily_reports_default = defineTool3({
  name: "list_daily_reports",
  title: "\u0627\u0644\u062A\u0642\u0627\u0631\u064A\u0631 \u0627\u0644\u064A\u0648\u0645\u064A\u0629",
  description: "List recent daily reports visible to the signed-in user. Optional filters: officeId, fromDate/toDate (YYYY-MM-DD), and limit (1\u2013100, default 20).",
  inputSchema: {
    officeId: z.string().optional().describe("Filter by office id."),
    fromDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Inclusive start date."),
    toDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Inclusive end date."),
    limit: z.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ officeId, fromDate, toDate, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = db3(ctx).from("daily_reports").select(
      "id, office_id, submitted_by, report_date, submitted_at, deployment_count, incidents_count, violations_count, deaths_count, events_count, visits_count, visitors_in, visitors_out, vehicles_count, processions_count"
    ).order("report_date", { ascending: false }).limit(limit);
    if (officeId) q = q.eq("office_id", officeId);
    if (fromDate) q = q.gte("report_date", fromDate);
    if (toDate) q = q.lte("report_date", toDate);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { reports: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-daily-report.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.108.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
function db4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_daily_report_default = defineTool4({
  name: "get_daily_report",
  title: "\u062A\u0641\u0627\u0635\u064A\u0644 \u062A\u0642\u0631\u064A\u0631 \u064A\u0648\u0645\u064A",
  description: "Fetch the full row of a single daily report by id.",
  inputSchema: { id: z2.string().uuid().describe("Daily report UUID.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await db4(ctx).from("daily_reports").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Report not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { report: data }
    };
  }
});

// src/lib/mcp/tools/list-emergencies.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.108.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
function db5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_emergencies_default = defineTool5({
  name: "list_emergencies",
  title: "\u0627\u0644\u062D\u0627\u0644\u0627\u062A \u0627\u0644\u0637\u0627\u0631\u0626\u0629",
  description: "List emergencies visible to the signed-in user. Filter by status (active/acknowledged/resolved) or officeId.",
  inputSchema: {
    status: z3.enum(["active", "acknowledged", "resolved"]).optional(),
    officeId: z3.string().optional(),
    limit: z3.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, officeId, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = db5(ctx).from("emergencies").select("*").order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    if (officeId) q = q.eq("office_id", officeId);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { emergencies: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-emergency.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.108.1";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^4.4.3";
function db6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_emergency_default = defineTool6({
  name: "create_emergency",
  title: "\u0625\u0646\u0634\u0627\u0621 \u062D\u0627\u0644\u0629 \u0637\u0627\u0631\u0626\u0629",
  description: "Create a new emergency for the signed-in user's office. Location fields are optional.",
  inputSchema: {
    emergencyType: z4.string().min(1).max(120).describe("Short label, e.g. '\u062D\u0631\u064A\u0642'."),
    description: z4.string().min(1).max(2e3).describe("Details of the emergency."),
    locationMgrs: z4.string().max(64).optional(),
    lat: z4.number().min(-90).max(90).optional(),
    lng: z4.number().min(-180).max(180).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = db6(ctx);
    const userId = ctx.getUserId();
    const { data: profile, error: pErr } = await supabase.from("profiles").select("office_id, full_name_ar").eq("id", userId).maybeSingle();
    if (pErr || !profile) {
      return { content: [{ type: "text", text: pErr?.message ?? "Profile not found" }], isError: true };
    }
    const { data, error } = await supabase.from("emergencies").insert({
      reported_by: userId,
      reported_by_name: profile.full_name_ar ?? "",
      office_id: profile.office_id,
      emergency_type: input.emergencyType,
      description: input.description,
      location_mgrs: input.locationMgrs ?? null,
      lat: input.lat ?? null,
      lng: input.lng ?? null,
      status: "active"
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Emergency created: ${data.id}` }],
      structuredContent: { emergency: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "yqwspssnpeyvzhpdoqpy";
var mcp_default = defineMcp({
  name: "arba3een-ops-mcp",
  title: "Arba3een Ops MCP",
  version: "0.1.0",
  instructions: "Tools for the Arba3een operations app. All actions run as the signed-in user (RLS + role permissions apply). Use `whoami` to check role, `list_offices` / `list_daily_reports` / `get_daily_report` for context, `list_emergencies` to monitor incidents, and `create_emergency` to open a new incident for the user's office.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_offices_default,
    list_daily_reports_default,
    get_daily_report_default,
    list_emergencies_default,
    create_emergency_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
